name: Update Week Files from Index

on:
  push:
    branches: [ main ]
    paths: [ 'index.md' ]
  workflow_dispatch:

jobs:
  update-weeks:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        npm install js-yaml markdown-it
        
    - name: Extract weeks from index.md
      run: |
        node << 'EOF'
        const fs = require('fs');
        const yaml = require('js-yaml');
        const MarkdownIt = require('markdown-it');
        const md = new MarkdownIt();
        
        // Read index.md
        const content = fs.readFileSync('index.md', 'utf8');
        
        // Split content by week sections
        const sections = content.split(/^## Week \d+/m);
        const frontmatter = content.match(/^---\n[\s\S]*?\n---\n/);
        
        // Extract each week
        for (let i = 1; i < sections.length; i++) {
          const weekMatch = content.match(new RegExp(`## (Week \\d+[^\\n]*)([\\s\\S]*?)(?=## Week \\d+|## Thanksgiving|$)`));
          if (weekMatch) {
            const weekTitle = weekMatch[1];
            const weekContent = weekMatch[2];
            const weekNum = weekTitle.match(/Week (\d+)/)[1];
            
            const weekFile = `---
title: ${weekTitle}
---

# ${weekTitle}
${weekContent.trim()}
`;
            
            fs.writeFileSync(`week${weekNum}.md`, weekFile);
            console.log(`Updated week${weekNum}.md`);
          }
        }
        EOF
        
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add week*.md
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Auto-update week files from index.md"
          git push
        fi
